### ISSUE TITLE
Failed compiling on iOS

### ISSUE THREAD

**Issue by MiroCaseiro** [BlueChilli/flutter_uploader#10]
Hi. 
I installed the plugin in my project, I'm getting the error 'symbol(s) not found for architecture x86_64':

 ...
  "protocol witness table accessor for __C.NSObject : Swift.CustomStringConvertible in Foundation", referenced from:
      lazy protocol witness table accessor for type __C.NSHTTPURLResponse and conformance __C.NSObject : Swift.CustomStringConvertible in Foundation in flutter_uploader(SwiftFlutterUploaderPlugin.o)
      lazy protocol witness table accessor for type __C.NSNumber and conformance __C.NSObject : Swift.CustomStringConvertible in Foundation in flutter_uploader(SwiftFlutterUploaderPlugin.o)
  "(extension in Swift):Swift.Sequence.forEach((A.Element) throws -> ()) throws -> ()", referenced from:
      closure #1 ([__C.NSURLSessionDataTask], [__C.NSURLSessionUploadTask], [__C.NSURLSessionDownloadTask]) -> () in flutter_uploader.SwiftFlutterUploaderPlugin.(cancelWithTaskId in _2FC37A31E0123CB294FAAD4BBE953965)(Swift.String) -> () in flutter_uploader(SwiftFlutterUploaderPlugin.o)
      closure #1 ([__C.NSURLSessionDataTask], [__C.NSURLSessionUploadTask], [__C.NSURLSessionDownloadTask]) -> () in flutter_uploader.SwiftFlutterUploaderPlugin.(cancelAllTasks in _2FC37A31E0123CB294FAAD4BBE953965)() -> () in flutter_uploader(SwiftFlutterUploaderPlugin.o)
      closure #1 () -> () in flutter_uploader.SwiftFlutterUploaderPlugin.(saveToFileWithCompletion in _2FC37A31E0123CB294FAAD4BBE953965)(_: [flutter_uploader.SwiftFlutterUploaderPlugin.UploadFileInfo], _: [Swift.String : Any?]?, _: Swift.String, completion: (Swift.String?, __C.FlutterError?) -> ()) -> () in flutter_uploader(SwiftFlutterUploaderPlugin.o)
      flutter_uploader.SwiftFlutterUploaderPlugin.(makeRequest in _2FC37A31E0123CB294FAAD4BBE953965)(_: Swift.String, _: Foundation.URL, _: Swift.String, _: [Swift.String : Any?]?, _: Swift.String, _: Swift.Int, completion: (__C.NSURLSessionUploadTask?, __C.FlutterError?) -> ()) -> () in flutter_uploader(SwiftFlutterUploaderPlugin.o)
      flutter_uploader.SwiftFlutterUploaderPlugin.urlSession(_: __C.NSURLSession, task: __C.NSURLSessionTask, didCompleteWithError: Swift.Error?) -> () in flutter_uploader(SwiftFlutterUploaderPlugin.o)
  "_swift_unknownWeakLoadStrong", referenced from:
      closure #1 (Swift.String?, __C.FlutterError?) -> () in flutter_uploader.SwiftFlutterUploaderPlugin.(uploadTaskWithURLWithCompletion in _2FC37A31E0123CB294FAAD4BBE953965)(url: Foundation.URL, files: [Any], method: Swift.String, headers: [Swift.String : Any?]?, parameters: [Swift.String : Any?]?, tag: Swift.String?, completion: (__C.NSURLSessionUploadTask?, __C.FlutterError?) -> ()) -> () in flutter_uploader(SwiftFlutterUploaderPlugin.o)
  "__swift_FORCE_LOAD_$_swiftUIKit", referenced from:
      __swift_FORCE_LOAD_$_swiftUIKit_$_flutter_uploader in flutter_uploader(SwiftFlutterUploaderPlugin.o)
      __swift_FORCE_LOAD_$_swiftUIKit_$_flutter_uploader in flutter_uploader(MimeType.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftUIKit_$_flutter_uploader)
  "type metadata for Foundation.URL", referenced from:
      flutter_uploader.SwiftFlutterUploaderPlugin.(uploadTaskWithURLWithCompletion in _2FC37A31E0123CB294FAAD4BBE953965)(url: Foundation.URL, files: [Any], method: Swift.String, headers: [Swift.String : Any?]?, parameters: [Swift.String : Any?]?, tag: Swift.String?, completion: (__C.NSURLSessionUploadTask?, __C.FlutterError?) -> ()) -> () in flutter_uploader(SwiftFlutterUploaderPlugin.o)
      type metadata accessor for Foundation.URL? in flutter_uploader(SwiftFlutterUploaderPlugin.o)
  "_swift_retain", referenced from:
      outlined copy of Swift._VariantDictionaryBuffer<A, B><A, B where A: Swift.Hashable> in flutter_uploader(SwiftFlutterUploaderPlugin.o)
      flutter_uploader.SwiftFlutterUploaderPlugin.(enqueueMethodCall in _2FC37A31E0123CB294FAAD4BBE953965)(__C.FlutterMethodCall, (Any?) -> ()) -> () in flutter_uploader(SwiftFlutterUploaderPlugin.o)
      flutter_uploader.SwiftFlutterUploaderPlugin.(cancelWithTaskId in _2FC37A31E0123CB294FAAD4BBE953965)(Swift.String) -> () in flutter_uploader(SwiftFlutterUploaderPlugin.o)
      closure #1 ([__C.NSURLSessionDataTask], [__C.NSURLSessionUploadTask], [__C.NSURLSessionDownloadTask]) -> () in flutter_uploader.SwiftFlutterUploaderPlugin.(cancelWithTaskId in _2FC37A31E0123CB294FAAD4BBE953965)(Swift.String) -> () in flutter_uploader(SwiftFlutterUploaderPlugin.o)
      reabstraction thunk helper from @escaping @callee_guaranteed (@guaranteed [__C.NSURLSessionDataTask], @guaranteed [__C.NSURLSessionUploadTask], @guaranteed [__C.NSURLSessionDownloadTask]) -> () to @escaping @callee_unowned @convention(block) (@unowned __C.NSArray, @unowned __C.NSArray, @unowned __C.NSArray) -> () in flutter_uploader(SwiftFlutterUploaderPlugin.o)
      flutter_uploader.SwiftFlutterUploaderPlugin.(cancelAllTasks in _2FC37A31E0123CB294FAAD4BBE953965)() -> () in flutter_uploader(SwiftFlutterUploaderPlugin.o)
      closure #1 ([__C.NSURLSessionDataTask], [__C.NSURLSessionUploadTask], [__C.NSURLSessionDownloadTask]) -> () in flutter_uploader.SwiftFlutterUploaderPlugin.(cancelAllTasks in _2FC37A31E0123CB294FAAD4BBE953965)() -> () in flutter_uploader(SwiftFlutterUploaderPlugin.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Can you help me?

**Comment by onikiri2007** [comment]
it compiles fine from new project - flutter create.
Have you try that?

if that works, your ios project might be old. try delete the ios folder and run flutter create .
