### ISSUE TITLE
Issue with gzip content encoding on Andorid

### ISSUE THREAD

**Issue by pietermeyerInfrasonic** [BlueChilli/flutter_uploader#12]
Hi

My backend server (Jetty(9.4.19.v20190610) responds with the content being gzip encoded. But on android this causes the plugin to return an empty response.

Can the issue please be investigated.  Please let me know if you need more details. Issue was 
temporarily resolved by changing requestBuilder.addHeader("Accept-Encoding", "br, gzip, deflate"); to requestBuilder.addHeader("Accept-Encoding", "deflate"); 

Kind Regards

**Comment by ened** [comment]
Could you provide a public endpoint for this?

**Comment by onikiri2007** [comment]
confirmed. OkHttp already does the gzip decoding transparently if we don't add Accept-Encoding header. the line has been removed. Thanks for the report.

Regards,

**Comment by pietermeyerInfrasonic** [comment]
Hi

Apologies for the late feedback, thank you for resolving the issue so quickly.

Kind Regards

[icon.png]
PIETER MEYER Infrasonic Consulting (Pty) Ltd
19 Sovereign Road, Route 21 Corporate Park, Irene
Phone: +27 82 921 9880
Email: pieter@infrasonic.co.za<mailto:pieter@infrasonic.co.za>
