### ISSUE TITLE
cancelAll() or cancel(taskId) throwing exception

### ISSUE THREAD

**Issue by Ajit121** [BlueChilli/flutter_uploader#16]
cancelAll() or cancel(taskId) throwing exception in android and not cancelling. Its working fine in iOS.

I/WM-WorkerWrapper(15368): Work [ id=3ccd5a83-37ab-4d50-bc96-40e1403fca5b, tags={ flutter_upload_task, com.bluechilli.flutteruploader.UploadWorker } ] was cancelled
I/WM-WorkerWrapper(15368): java.util.concurrent.CancellationException: Task was cancelled.
I/WM-WorkerWrapper(15368): 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
I/WM-WorkerWrapper(15368): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
I/WM-WorkerWrapper(15368): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
I/WM-WorkerWrapper(15368): 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:284)
I/WM-WorkerWrapper(15368): 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:75)
I/WM-WorkerWrapper(15368): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
I/WM-WorkerWrapper(15368): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
I/WM-WorkerWrapper(15368): 	at java.lang.Thread.run(Thread.java:764)

**Comment by onikiri2007** [comment]
This is WorkManager logging in the exception to the Console but it's not actually raising the exception however there was an issue with cancellation when upload request was already inflight. it wasn't cancelling the request. Thanks for raising the issue. it's should fix in version 1.0.3+2
