### ISSUE TITLE
Understanding upload behaviour when app is not running

### ISSUE THREAD

**Issue by sndrox** [BlueChilli/flutter_uploader#19]
Apparently uploader.result.listen... is not called when task ends and the app is not running, am I wrong?

**Comment by ened** [comment]
At the moment, the uploader depends on a running App in order to connect back to the progress channel, so you are correct.

A future version of this plugin shall contain a child isolate (similar to how `firebase_messaging` and  `android_alarm_manager` are handling it.

**Comment by sndrox** [comment]
Thanks ened, got it.

Is there any trick you can think of that would let me understand whether an upload has ended "while I was away"?

**Comment by ened** [comment]
The plugin is using WorkManager on Android. I'm sure there is a API which we could expose to let you check using the returned `taskId`. Perhaps try it out first in your App you can add a simple method handler to your MainActivity on Android to check for a taskId.

I'm not sure about the iOS version, but it should be a similar principle.

**Comment by singlakaran** [comment]
@ened  when will you release new version?

**Comment by ened** [comment]
Going further, this plugin should call create a isolate-while-running that informs a callback when the upload has finished in the background. We can probably follow that `flutter_workmanager` has done.
