### ISSUE TITLE
File Upload Fail 

### ISSUE THREAD

**Issue by avootla1** [BlueChilli/flutter_uploader#25]
14  libsystem_pthread.dylib             0x000000010f4f63fd start_wqthread + 13
13  libsystem_pthread.dylib             0x000000010f4f66b3 _pthread_wqthread + 583
12  libdispatch.dylib                   0x000000010f125330 _dispatch_worker_thread2 + 97
11  libdispatch.dylib                   0x000000010f124ad3 _dispatch_root_queue_drain + 355
10  libdispatch.dylib                   0x000000010f117d49 _dispatch_async_redirect_invoke + 817
9   libdispatch.dylib                   0x000000010f1186be _dispatch_continuation_pop + 440
8   libdispatch.dylib                   0x000000010f115d02 _dispatch_client_callout + 8
7   libdispatch.dylib                   0x000000010f114ccf _dispatch_call_block_and_release + 12
6   Foundation                          0x000000010c953f5b __NSOQSchedule_f + 227
5   Foundation                          0x000000010c94e1f4 -[__NSOperationInternal _start:] + 688
4   Foundation                          0x000000010c95131a -[NSBlockOperation main] + 68
3   Foundation                          0x000000010c951412 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
2   CFNetwork                           0x000000010fb82002 __51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke.182 + 255
1   Runner                              0x000000010a375b33 $s16flutter_uploader26SwiftFlutterUploaderPluginC10urlSession_4task20didCompleteWithErrorySo12NSURLSessionC_So0N4TaskCs0M0_pSgtFTo + 163
0   Runner                              0x000000010a3744b7 $s16flutter_uploader26SwiftFlutterUploaderPluginC10urlSession_4task20didCompleteWithErrorySo12NSURLSessionC_So0N4TaskCs0M0_pSgtF + 13207

I get this error whenever I try to upload a long duration recording (usually over 30 mins). Everything works fine when I try to upload a smaller one.

**Comment by ened** [comment]
Hi @avootla1 - do you have more details on when the issue happened exactly?

**Comment by avootla1** [comment]
Hi @ened , Thanks for your quick response. 
I get this error whenever I try to upload a long duration recording (usually over 30 mins). Everything works fine when I try to upload a smaller one.

**Comment by onikiri2007** [comment]
this should be fixed with 1.2.0
