### ISSUE TITLE
Ios is not uploading multiple images

### ISSUE THREAD

**Issue by yashj-occipitaltech** [BlueChilli/flutter_uploader#27]
The android app is working fine and uploading multiple images but the ios one is only uploading the first one . I have logged the outputs and flutter uploader is receiving  the exact number of files in the files list but it is only uploading the first one. Can you tell me what's the issue here ?
Thanks for the plugin !

**Comment by rota2000** [comment]
I have the same issue

**Comment by onikiri2007** [comment]
this should be fixed with 1.2.0
