### ISSUE TITLE
FlutterUploader.result never fires events

### ISSUE THREAD

**Issue by thosakwe** [BlueChilli/flutter_uploader#36]
Hi, and thanks for the awesome plug-in. I'm developing an app where I'm using background uploads for multi-media posts. I want to use `uploader.result.listen(...)` to show a small notification when posts successfully upload, but the event never fires.

I am 100% sure that the requests sends correctly, though. In fact, `flutter_uploader` logs some information to the console containing the response:

```
flutter: Task: chillisource.flutter_uploader.upload.background.1
    "Content-Type" =     (
        "application/json"
    );
    Server =     (
        angel
    );
    "Transfer-Encoding" =     (
        Identity
    );
    "x-content-type-options" =     (
        nosniff
    );
    "x-frame-options" =     (
        SAMEORIGIN
    );
    "x-ratelimit-limit" =     (
        1000
    );
    "x-ratelimit-remaining" =     (
        987
    );
    "x-ratelimit-reset" =     (
        1573660666
    );
    "x-xss-protection" =     (
        "1; mode=block"
    );
} } and status: 200
```

The question is - why does the `FlutterUploader` class never receive a notification that the upload worked? Thanks.

**Comment by onikiri2007** [comment]
is this iOS or android?  have you tried with both? I can't really help you without more information

**Comment by thosakwe** [comment]
Running on iOS simulator; haven't tried with Android.
