### ISSUE TITLE
Headers Config (Content-Type)

### ISSUE THREAD

**Issue by ainulya16** [BlueChilli/flutter_uploader#38]
files is failed to upload after set header of content type to "application/octet-stream".

here is error response below:

>flutter: exception: taskId: chillisource.flutter_uploader.upload.background.5, status:UploadTaskStatus(4), statusCode:400, code:upload_error, message:Error in call to API function "files/upload": Bad HTTP "Content-Type" header: "multipart/form-data; boundary=alamofire.boundary.3b1254f2854aa177,application/octet-stream".  Expecting one of "application/octet-stream", "text/plain; charset=dropbox-cors-hack".}, tag:upload

**Comment by ened** [comment]
Hi @ainulya16 please try the new enqueueRaw method in the uploaded class.

**Comment by ainulya16** [comment]
which version?

**Comment by onikiri2007** [comment]
try 1.2.0

**Comment by ainulya16** [comment]
i did but still same. i am using "enqueue" not enqueueBinary" to upload multiple files.

**Comment by ened** [comment]
Hi @ainulya16 in that case call enqueueBinary for each of your files. Please check how exactly it endpoints expects the data.

**Comment by ainulya16** [comment]
i did it, but seemed this package replace my customer header for "application/octet-stream" or whatever it is.

**Comment by spiritinlife** [comment]
I had the same issue @ainulya16 . Did this pr if you want to take a look https://github.com/BlueChilli/flutter_uploader/pull/54
@ened

**Comment by ened** [comment]
@ainulya16 The PR at #54 got merged. You can test the changes using:

```
dependency_overrides:
  flutter_uploader:
    git:
      url: https://github.com/BlueChilli/flutter_uploader
```
