### ISSUE TITLE
java.lang.IllegalArgumentException: Parameter specified as non-null is null

### ISSUE THREAD

**Issue by ragnor-rs** [BlueChilli/flutter_uploader#40]
flutter_uploader: 1.2.0
OS: Android

This is because `MimeTypeMap.getSingleton().getMimeTypeFromExtension("log")` is null

Stack trace
```
[  +67 ms] D/UploadWorker( 9033): attaching file: /data/user/0/ru.fl.flmobile/cache/appium.log
[        ] W/System.err( 9033): java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter $this$toMediaTypeOrNull
[        ] W/System.err( 9033): 	at okhttp3.MediaType$Companion.parse(MediaType.kt)
[        ] W/System.err( 9033): 	at okhttp3.MediaType.parse(MediaType.kt)
[        ] W/System.err( 9033): 	at com.bluechilli.flutteruploader.UploadWorker.doWork(UploadWorker.java:153)
[        ] W/System.err( 9033): 	at androidx.work.Worker$1.run(Worker.java:85)
[        ] W/System.err( 9033): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
[        ] W/System.err( 9033): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
[        ] W/System.err( 9033): 	at java.lang.Thread.run(Thread.java:761)
[   +5 ms] I/WM-WorkerWrapper( 9033): Worker result FAILURE for Work [ id=fee32
```

**Comment by ened** [comment]
This is fixed, at least in the master branch. Please check out the latest code.

**Comment by volser** [comment]
I got this error too.
How to reproduce: try to upload a file with name `.nomedia`

`getMimeTypeFromExtension` returns null
> The MIME type for the given extension or null if there is none.
https://developer.android.com/reference/android/webkit/MimeTypeMap#getMimeTypeFromExtension(java.lang.String)

PR:
https://github.com/BlueChilli/flutter_uploader/pull/93

**Comment by lanistor** [comment]
@ened How to fix it in 1.x versions?

**Comment by ened** [comment]
@lanistor You can try renaming the file beforehand to something like log.txt.

Thinking that the plug-in should not determine the mime type by itself and instead delegate it to the user.

**Comment by lanistor** [comment]
@ened Or add a parameter on `uploader.enqueue` function to pass to android? If MimeType is necessary, this seems a better way to resolve.

**Comment by ened** [comment]
@lanistor yes, exactly. The idea is to pass mimeType when scheduling the upload and remove all _detection_ code from the native side.

**Comment by lanistor** [comment]
@ened I saw this is resolved in branch master, not in tag 1.2.0, i guess this may be resolved in version 2.x.
But we are using 1.2.x, and 2.x is not compatible with our project.
So will you repaire it in version 1.x?

**Comment by ened** [comment]
@lanistor no - unfortunately there is not enough time to maintain 1.2.x for me. I'd be happy to review & merge a pull a request though,

**Comment by lanistor** [comment]
@ened I added i [pull request](https://github.com/fluttercommunity/flutter_uploader/pull/136) to resolve it, had run test case.
I didn't found a branch of 1.x, so i add `branch master` as base, but this will be wrong. May you checkout a new branch to receive this pull request?
