### ISSUE TITLE
uploader.result.listen call twice

### ISSUE THREAD

**Issue by tony123S** [BlueChilli/flutter_uploader#49]
```
  try {
      final result = await InternetAddress.lookup('google.com');
      if (result.isNotEmpty && result[0].rawAddress.isNotEmpty) {
        final taskId = await uploader.enqueue(
            url:
                'https://xxxx',
            files: files,
            data: {
             ....
            },
            method: UploadMethod.POST,
            showNotification: true,
            tag: title);

        final subscription = uploader.result.listen((result) async {
          print("response " + result.response);
        }, onError: (ex, stacktrace) {
          print(ex.toString());
        });
      }
    } catch (e) {
      ...
    }
  }
```

When first time I call this,  `uploader.result.listen` will only print one. But if I call this method again,  `uploader.result.listen` will call twice. Why?

**Comment by onikiri2007** [comment]
Do u cancel ur subscription before subscribing again 2nd time? Then you are attaching listener twice. You do not need to call listen twice though

**Comment by tony123S** [comment]
How do I cancel listener?

**Comment by tony123S** [comment]
fixed.

**Comment by UzairSun93** [comment]
@tony123S how this has to be fixed can you please specify the steps ?

**Comment by tony123S** [comment]
@UzairSun93 

dispose it

 ```
@override
  void dispose() {
    _subscription.cancel();
    super.dispose();
  }
```

**Comment by crsmillan** [comment]
@tony123S  this isn't enough , my code still call multiple times the same task

**Comment by tony123S** [comment]
@crsmillan  maybe paste your code?

**Comment by sara-shokry** [comment]
@tony123S i'v more than one task, and the result called multiple times for each one  should i cancel each one when i received successful result ??
