### ISSUE TITLE
result message from server is null but shown on log

### ISSUE THREAD

**Issue by majordio** [BlueChilli/flutter_uploader#51]
![image](https://user-images.githubusercontent.com/50364640/81491405-e9ac9800-92c0-11ea-8b30-b9256cc322fe.png)
![image](https://user-images.githubusercontent.com/50364640/81491411-fa5d0e00-92c0-11ea-8cda-ee9cbd4fe204.png)

**Comment by ened** [comment]
Which upload method did you use? Please share a few more details.

**Comment by majordio** [comment]
hi im using the `uploader.enqueue()` method

upload code: 
>var upload = await uploader.enqueue(
      url: url, 
      files: [FileItem(filename: file.path.split('/').last, savedDir: file.parent.path, fieldname:"file[]")],
      method: UploadMethod.POST,
      data: {
        "order_type": "$orderType",
        "type_id": "$type",
        "order_id": "$id",
      }, 
      showNotification: true, 
      tag: "Upload File #$orderType.$type.$id"
    );
thanks

**Comment by ened** [comment]
Please try the PR here https://github.com/BlueChilli/flutter_uploader/pull/70

There has been work done on progress / result storage and it may cover your problem as well.

**Comment by majordio** [comment]
Hi, tried the PR but still wont show the response, nice new functionalities though, specially on the notifications
![image](https://user-images.githubusercontent.com/50364640/88152061-102e6e00-cc36-11ea-9dfe-1da76ce05fcb.png)

**Comment by ened** [comment]
Could you refer to this file https://github.com/BlueChilli/flutter_uploader/blob/c9aedd412abb515b50a2b1b6319c682d253aa802/example/test_driver/flutter_uploader_test.dart or even build a test case to showcase the problem?

**Comment by majordio** [comment]
I got it now, fixed by modifying the server response Content-Type to application/json instead of text/html. Thanks for the help.
