### ISSUE TITLE
Is it possible to send base64 file in body instead of form-data ?

### ISSUE THREAD

**Issue by vince83110** [BlueChilli/flutter_uploader#55]
I use an API where I need to pass base64encoded File String to post my file.

And your plugin allows to avoid the error I have for now : when my user leave the app, the file is not sent, and won't be send...
I tried it, it's perfect, but is there any way to change form-data format ?

I checked your code, and honestly didn't see where I could change it..

**Comment by ened** [comment]
Please take a look at the enqueueBinary method.
