### ISSUE TITLE
How to upload to Firebase Cloud Storage

### ISSUE THREAD

**Issue by syonip** [BlueChilli/flutter_uploader#56]
Hi, 
Wanted to check if there's a way to use this for saving files to Firebase Cloud Storage. 
The firebase plugin doesn't provide a url to upload to.

Thanks.

**Comment by ened** [comment]
Not at this moment, @syonip. FlutterFire is shifting gears currently, and perhaps it's part of the work done there.

I would suggest to look at `flutter_workmanager` and schedule a repeating task that way. Once the upload in the task is done, stop scheduling it.

**Comment by syonip** [comment]
OK, thanks.
