### ISSUE TITLE
Data cannot occupy more than 10240 bytes when serialized

### ISSUE THREAD

**Issue by tony123S** [BlueChilli/flutter_uploader#58]
My repo class

  ```
Future submitImages(
      FlutterUploader uploader,List<dynamic> imageList) async {
    var savedDir = await getApplicationDocumentsDirectory();
    String appDocPath = savedDir.path;
    List<FileItem> files = List<FileItem>();
    var count = 0;

    files = imageList.map((imageUrl) {
      final file = FileItem(
          filename: FileUtils.basename(imageUrl),
          savedDir: appDocPath,
          fieldname: 'images[$count]');

      count++;
      return file;
    }).toList();

        await uploader.enqueue(
            url:
                'https://xxx.com',
            files: files,
            data: {...
            },
            method: UploadMethod.POST,
            showNotification: false,
            tag: title);
  }
```

**Page A** 

 ```
 StreamSubscription<UploadTaskResponse> _subscription;
  FlutterUploader uploader = FlutterUploader();

  @override
  void initState() {
    super.initState();

    _subscription = uploader.result.listen(
      (result) {
        _bloc.getList();
      },
      onError: (ex, stacktrace) {
        print("Error from PageA :  " + ex.toString());
      },
    );
  }
```

**Error**

`Error from PageA :  taskId: 7f5cf18b-ec62-44c6-ac41-fd73da0fcd0e, status:UploadTaskStatus(4), statusCode:500, code:upload error, message:java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized}, tag:g4gg`

I use api tool to test, my api is working.
`

**Comment by bachras** [comment]
I am having same issue with 3.0.0-beta.1

**Comment by ened** [comment]
@bachras please open a new ticket with detailed stack trace, logs and ideally a example project to show the problem. Thank you.

**Comment by bachras** [comment]
Thank you for prompt response. I just found an answer in https://github.com/fluttercommunity/flutter_uploader/issues/53 . API was sending long server exception response. Thanks

**Comment by bachras** [comment]
@ened I have fully implemented your package into my app and now I have same error when I receive large json response. Do you know any workaround for large than 10kb responses. I was trying to compress response on backend and decompress flutter but I need response in bytes and file uploader gives me string as response. Any ideas how to get response in bytes List<int> format. Thank you in advance

**Comment by ened** [comment]
@bachras please open a new ticket with details on that comment. I think the uploader should do a lot less - parsing the response (& forcing a JSON response) may not be what is needed. We could, like you said, just provide a way to get the response bytes.
