### ISSUE TITLE
cannot find symbol import com.bluechilli.flutteruploader.FlutterUploaderPlugin;

### ISSUE THREAD

**Issue by kedark-ix** [BlueChilli/flutter_uploader#61]
I have upgraded my flutter recently which introduced a new issue to me

**Log of the issue is** 

`\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:15: error: cannot find symbol
import com.bluechilli.flutteruploader.FlutterUploaderPlugin;
                                     ^
  symbol:   class FlutterUploaderPlugin
  location: package com.bluechilli.flutteruploader`

`\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:48: error: cannot find symbol
    FlutterUploaderPlugin.registerWith(registry.registrarFor("com.bluechilli.flutteruploader.FlutterUploaderPlugin"));
    ^
  symbol:   variable FlutterUploaderPlugin
  location: class GeneratedPluginRegistrant`

**The output of the flutter doctor -v is bellow**

[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.900], locale en-US)
    • Flutter version 1.17.5 at C:\flutter
    • Framework revision 8af6b2f038 (2 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\kedar\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\kedar\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\kedar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

I have tried by cleaning the cache & flutter clean but still, the issue is there..

**Comment by ened** [comment]
@kedark-ix hi!

Can you please give my WIP fork a try:

In pubspec.yaml, add this to the `dependency_overrides` section:

```
  flutter_uploader:
    git:
      url: https://github.com/ened/flutter_uploader.git
      ref: android-embedding-v2
```

**Comment by kedark-ix** [comment]
Fix my issue. What I did is just clean the local code and again clone the code. In the new code, it is not showing me an error.
