### ISSUE TITLE
Notification click doesn't work

### ISSUE THREAD

**Issue by utkarshmarwaha** [BlueChilli/flutter_uploader#69]
I am trying to upload a large file in parts and and would want to allow user to click on notification showing progress to open a certain page on the app where he can see the list of parts uploaded.

But clicking on notification doesn't work. Please suggest.

**Comment by ened** [comment]
Can you try adding a intent filter for your main activity:

```
<intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
</intent-filter>
```

**Comment by ened** [comment]
Also, is this on Android / iOS?

**Comment by utkarshmarwaha** [comment]
@ened  this was for android.

In iOS, notifications doesn't show since its not supported.

I'll check with the intent filter as well.

**Comment by ened** [comment]
> @ened this was for android.
> 
> In iOS, notifications doesn't show since its not supported.

Ah, my bad.


Yes please check & also check the logcat output.

**Comment by ened** [comment]
You could try the PR (it has instruction on testing) that is linked here.

**Comment by ened** [comment]
Please try with the current `master` branch.
