### ISSUE TITLE
data is not being sent on POST calls

### ISSUE THREAD

**Issue by chornbe** [BlueChilli/flutter_uploader#71]
Doing a pretty basic upload with some key/value pairs added to the data element. When I inspect the req.body in my node API, the body is empty. I'd expect the data information to be there just like when I do a regular http.post(...) call using its body parameter.

```
        final taskId = await uploader.enqueue(
          url: url,
          files: [
            FileItem(
              filename: dummyFilename,
              savedDir: tmp.path,
              fieldname: "file",
            ),
          ],
          method: UploadMethod.POST,
          headers: {"x-access-token": token},
          data: {
            "eventId": _event.id.toString(),
            "captureTime": DateTime.now().toIso8601String(),
            "longitude": myLocation.longitude.toString(),
            "latitude": myLocation.latitude.toString(),
            "nickname": witnessUser.nickname,
            "caption": "Video captured by caller",
            "description": "Video captured by caller",
          },
          tag: "video upload",
        );
```
In my nodeJs API function, req.body is empty.

But, doing a regular http.post...
```
        Map<String, String> parms = {
          "videoData": b64,
          "eventId": _event.id.toString(),
          "captureTime": DateTime.now().toIso8601String(),
          "longitude": myLocation.longitude.toString(),
          "latitude": myLocation.latitude.toString(),
          "nickname": witnessUser.nickname,
          "caption": "Video captured by caller",
          "description": "Video captured by caller",
        };
        http.Response resp = await http.post(
          url,
          headers: {"x-access-token": token},
          body: parms,
        );
```
In my nodeJs API function, req.body is populated as I'd expect. 

I'd really love to move this into a background operation, and otherwise, it seems flutter_uploader is ideal for my wants. Am I misunderstanding the data paramter in the flutter_uploader? 

Thanks!

**Comment by ened** [comment]
I think you may need to use something like a busboy middleware to extract the fields. The request on the top (using flutter_uploader) creates a `multipart/form-data` request whereas the one on the bottom posts json directly.

**Comment by chornbe** [comment]
This is me walking away shaking my head because... duh! Dumbass me. Thanks!

**Comment by ened** [comment]
No worries. Btw, would be great if you have a minute to test #70 - should be good for your use case.  👍
