### ISSUE TITLE
How to send nested object in data

### ISSUE THREAD

**Issue by agnoam** [BlueChilli/flutter_uploader#73]
How do I send a nested object type: 
```
{
  'field': {
    'key': 'value',
    'key2': 2
  }
}
```
in `data` field of background_uploader ?

**Comment by agnoam** [comment]
Hey, I found a fix for this. 
It's a little bit messy one, just put a `jsonEncode()` 
on the nested object and send it as a string

**Comment by ened** [comment]
This is actually the recommended way. Consider that the plugin sends a multipart/form-data request, in which the contents are sent as form fields.
The plugin _could_ encode the payload, but should be a decision done by the user of the plugin. 

We will address this as a documentation update in the future, thank you.
