### ISSUE TITLE
Upload not working on Android 9 and 10

### ISSUE THREAD

**Issue by rahul-alld** [BlueChilli/flutter_uploader#76]
Hi,
Using flutter_uploader(latest version), I'm trying to upload images/videos on server. Same is working fine on Android 7. But in Android 9 and 10, it is failing. In fact request is not reaching to the server.
Please guide to fix the problem.

**Comment by ened** [comment]
@rahul-alld can you please try the latest version from git

**Comment by ened** [comment]
Please open a new ticket with reproducible steps.
