### ISSUE TITLE
Uploaded video not received in server

### ISSUE THREAD

**Issue by SaravanarajaGITHUB** [BlueChilli/flutter_uploader#8]
Trying to upload a video in background from my flutter app,
Done all the mentioned steps for android integration, able to see the video uploading dialogue in notification bar & getting a success message too but video is not received in server, what i'm missing ? or what wrong with the code ? (code attached below)

```
 FlutterUploader uploader = FlutterUploader();
    StreamSubscription _resultSubscription;
  String _taskId;

  @override
  void initState() {
    super.initState();
    _resultSubscription = uploader.result.listen((result) {
      print("***********************${result.status}");
      final _stateProvider = new StateProvider();
      _stateProvider.notify(ObserverState.UPDATE);
      Navigator.of(context).popUntil(ModalRoute.withName(Routes.PLAY_NOW));
    }, onError: (ex, stacktrace) {
      print("************************** $ex ---- $stacktrace");
    });
  }

@override
  void dispose() {
    super.dispose();
    _resultSubscription.cancel();
  }
  
  taskId = uploadInfo(
        context, ModalRoute.of(context).settings.arguments, uploader) as String;
		
		Future _uploadInfo(BuildContext context, ContestantDetails contestantDetails,
    FlutterUploader uploader) async {
  print(contestantDetails.filePath);
  String savedDir = contestantDetails.filePath;
  String filename = p.basename(contestantDetails.filePath);
  print("Path name $filename");

  final taskId = await uploader.enqueue(
      url:
          "http://holein1hero.com/api/uploadApi/p2lbgWkFrykA4QyUmpHihzmc5BNzIABq",
      method: UplaodMethod.POST,
      files: [FileItem(filename: "", savedDir: savedDir, fieldname: "file")],
      data: {
        "first_name": contestantDetails.firstName,
        "last_name": contestantDetails.lastName,
        "email": contestantDetails.email,
        "unique_id": contestantDetails.uniqueId,
        "contest_id": contestantDetails.contestId,
        "payment_transaction_id": contestantDetails.paymentTransactionId,
        "schedule_date": contestantDetails.scheduleDate,
        "latitude": contestantDetails.latitude,
        "longitude": contestantDetails.longitude,
        "created_at": "jflasdkfjl;kj"
      },
showNotification: true);
  print("**************** task id $taskId");

  return taskId;
  
}
```

**Comment by onikiri2007** [comment]
update package to 1.0.3
try

FlutterUploader uploader) async {
  print(contestantDetails.filePath);
  String savedDir = p.dirname(contestantDetails.filePath);
  String filename = p.basename(contestantDetails.filePath);
  print("Path name $filename");

 // filename and savedDir both required

  final taskId = await uploader.enqueue(
      url:
          "http://holein1hero.com/api/uploadApi/p2lbgWkFrykA4QyUmpHihzmc5BNzIABq",
      method: UploadMethod.POST,
      files: [FileItem(filename: filename, savedDir: savedDir, fieldname: "file")],
      data: {
        "first_name": contestantDetails.firstName,
        "last_name": contestantDetails.lastName,
        "email": contestantDetails.email,
        "unique_id": contestantDetails.uniqueId,
        "contest_id": contestantDetails.contestId,
        "payment_transaction_id": contestantDetails.paymentTransactionId,
        "schedule_date": contestantDetails.scheduleDate,
        "latitude": contestantDetails.latitude,
        "longitude": contestantDetails.longitude,
        "created_at": "jflasdkfjl;kj"
      },
