### ISSUE TITLE
How we can upload Multiple Files Using This Package? Please Reply

### ISSUE THREAD

**Issue by Zeeshan0201** [BlueChilli/flutter_uploader#9]

**Comment by onikiri2007** [comment]
You can either do below

final taskId = await uploader.enqueue(
  url: "your upload link", //required: url to upload to
  files: [FileItem(filename: filename, savedDir: savedDir, fieldname:"file"),
FileItem(filename:"secondfile.jpeg", savedDir: savedDir, fieldname:"file"),
...
], // required: list of files that you want to upload
  method: UplaodMethod.POST, // HTTP method  (POST or PUT or PATCH)
  headers: {"apikey": "api_123456", "userkey": "userkey_123456"},
  data: {"name": "john"}, // any data you want to send in upload request
  showNotification: false, // send local notification (android only) for upload status
  tag: "upload 1"); // unique tag for upload task
);

or

enqueue multiple upload task with different files

**Comment by Zeeshan0201** [comment]
@onikiri2007 and how we can enable option for selecting multiple file?

**Comment by Zeeshan0201** [comment]
@onikiri2007 how can i set multiple files as 

> files: [FileItem(filename: filename, savedDir: savedDir, fieldname:"file[0]"),
> FileItem(filename:"secondfile.jpeg", savedDir: savedDir, fieldname:"file"[1])]

as i am not able to do by this..
![Screenshot from 2019-08-06 12-31-01](https://user-images.githubusercontent.com/45591301/62517960-10c3ce00-b846-11e9-9804-b016de286244.png)

**Comment by SrengBona** [comment]
Hello guy, who can tell me about "FileItem(filename:"secondfile.jpeg", savedDir: savedDir, fieldname:"file")" variable savedDir.

Bona SR.
Thank you!

**Comment by SrengBona** [comment]
final uploader = FlutterUploader();
    String uid = await FlutterSecureStorage().read(key: "getTocken");
    final taskId = await uploader.enqueue(
      url: mainUrl + 'merchant/upload-galleries',
      files: [FileItem(filename: images[0].name.toString(), savedDir:"", fieldname:"file"),], 
      method: UploadMethod.POST,
      headers: {HttpHeaders.authorizationHeader: uid,},
      showNotification: false, 
    );

    print(taskId);


Here is coding... but it's not work!

Show error like below:
Unhandled Exception: MissingPluginException(No implementation found for method enqueue on channel flutter_uploader)
E/flutter (10832): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (10832): <asynchronous suspension>
E/flutter (10832): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (10832): #2      FlutterUploader.enqueue (package:flutter_uploader/src/flutter_uploader.dart:69:30)
E/flutter (10832): #3      _ListImagesState._uploadFiles (package:merchantside/merchantside/listImages.dart:46:35)
E/flutter (10832): <asynchronous suspension>
